onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /processor_tb/clk
add wave -noupdate /processor_tb/reset
add wave -noupdate /processor_tb/i_processor/i_reg_bank/regs
add wave -noupdate /processor_tb/i_processor/Clk
add wave -noupdate /processor_tb/i_processor/Reset
add wave -noupdate /processor_tb/i_processor/IAddr
add wave -noupdate /processor_tb/i_processor/IDataIn
add wave -noupdate /processor_tb/i_processor/DAddr
add wave -noupdate /processor_tb/i_processor/DRdEn
add wave -noupdate /processor_tb/i_processor/DWrEn
add wave -noupdate /processor_tb/i_processor/DDataOut
add wave -noupdate /processor_tb/i_processor/DDataIn
add wave -noupdate /processor_tb/i_processor/sys_OpCode
add wave -noupdate /processor_tb/i_processor/sys_RegDst
add wave -noupdate /processor_tb/i_processor/sys_Jump
add wave -noupdate /processor_tb/i_processor/sys_Branch
add wave -noupdate /processor_tb/i_processor/sys_MemRead
add wave -noupdate /processor_tb/i_processor/sys_MemToReg
add wave -noupdate /processor_tb/i_processor/sys_ALUOp
add wave -noupdate /processor_tb/i_processor/sys_MemWrite
add wave -noupdate /processor_tb/i_processor/sys_ALUSrc
add wave -noupdate /processor_tb/i_processor/sys_RegWrite
add wave -noupdate /processor_tb/i_processor/sys_Zflag
add wave -noupdate /processor_tb/i_processor/sys_rs
add wave -noupdate /processor_tb/i_processor/sys_rt
add wave -noupdate /processor_tb/i_processor/sys_rd
add wave -noupdate /processor_tb/i_processor/sys_A3
add wave -noupdate /processor_tb/i_processor/sys_funct
add wave -noupdate /processor_tb/i_processor/sys_immediate
add wave -noupdate /processor_tb/i_processor/sys_immediate_extended
add wave -noupdate /processor_tb/i_processor/sys_immediate_shifted
add wave -noupdate /processor_tb/i_processor/sys_Branch_address
add wave -noupdate /processor_tb/i_processor/sys_PCp4_Branch
add wave -noupdate /processor_tb/i_processor/sys_PCNext
add wave -noupdate /processor_tb/i_processor/sys_immJ
add wave -noupdate /processor_tb/i_processor/sys_alu_control
add wave -noupdate /processor_tb/i_processor/PC
add wave -noupdate /processor_tb/i_processor/PCp4
add wave -noupdate /processor_tb/i_processor/Jump_address
add wave -noupdate /processor_tb/i_processor/sys_Rd1
add wave -noupdate /processor_tb/i_processor/sys_Rd2
add wave -noupdate /processor_tb/i_processor/sys_Wd3
add wave -noupdate /processor_tb/i_processor/sys_OpB
add wave -noupdate /processor_tb/i_processor/sys_Res
add wave -noupdate /processor_tb/i_processor/PCp4_1
add wave -noupdate /processor_tb/i_processor/sys_instruction_1
add wave -noupdate /processor_tb/i_processor/sys_RegDst_2
add wave -noupdate /processor_tb/i_processor/sys_Jump_2
add wave -noupdate /processor_tb/i_processor/sys_Branch_2
add wave -noupdate /processor_tb/i_processor/sys_MemRead_2
add wave -noupdate /processor_tb/i_processor/sys_MemToReg_2
add wave -noupdate /processor_tb/i_processor/sys_ALUOp_2
add wave -noupdate /processor_tb/i_processor/sys_MemWrite_2
add wave -noupdate /processor_tb/i_processor/sys_ALUSrc_2
add wave -noupdate /processor_tb/i_processor/sys_RegWrite_2
add wave -noupdate /processor_tb/i_processor/PCp4_2
add wave -noupdate /processor_tb/i_processor/sys_Rd1_2
add wave -noupdate /processor_tb/i_processor/sys_Rd2_2
add wave -noupdate /processor_tb/i_processor/sys_immediate_extended_2
add wave -noupdate /processor_tb/i_processor/sys_rt_2
add wave -noupdate /processor_tb/i_processor/sys_rd_2
add wave -noupdate /processor_tb/i_processor/sys_Jump_3
add wave -noupdate /processor_tb/i_processor/sys_Branch_3
add wave -noupdate /processor_tb/i_processor/sys_Branch_address_3
add wave -noupdate /processor_tb/i_processor/sys_MemRead_3
add wave -noupdate /processor_tb/i_processor/sys_MemToReg_3
add wave -noupdate /processor_tb/i_processor/sys_MemWrite_3
add wave -noupdate /processor_tb/i_processor/sys_RegWrite_3
add wave -noupdate /processor_tb/i_processor/sys_Rd2_3
add wave -noupdate /processor_tb/i_processor/sys_Zflag_3
add wave -noupdate /processor_tb/i_processor/sys_Res_3
add wave -noupdate /processor_tb/i_processor/sys_A3_3
add wave -noupdate /processor_tb/i_processor/sys_MemToReg_4
add wave -noupdate /processor_tb/i_processor/sys_RegWrite_4
add wave -noupdate /processor_tb/i_processor/sys_Res_4
add wave -noupdate /processor_tb/i_processor/sys_A3_4
add wave -noupdate /processor_tb/i_processor/sys_dDataIn_4
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
